- src/Orchestration/Saga/Cache/BaseCacheHandler.php
- src/Orchestration/Saga/Cache/CacheHandlerInterface.php
Define the cache interface and abstract class.
**Checklist:**
> develop: define the cache interface and abstract class.

- develop/app/Anser/Orchestrators/UserOrchestrator.php
- develop/app/Config/Routes.php
- develop/app/Controllers/v1/Redis.php
- develop/app/Controllers/v1/Serialize.php
- develop/composer.json
- develop/composer.lock
- src/Exception/RedisException.php
- src/Orchestration/Saga/Cache/BaseCacheHandler.php
- src/Orchestration/Saga/Cache/CacheHandlerInterface.php
- src/Orchestration/Saga/Cache/Redis/RedisHandler.php
The feature that serialize orchestrator into redis has been implemented.
But test case and use case have not been added yet.
**Checklist:**
> develop: The feature that serialize orchestrator into redis has been implemented.

- develop/app/Config/Filters.php
- develop/app/Config/Routes.php
- develop/app/Database/Migrations/2023-01-05-113858_Product.php
- develop/app/Database/Migrations/2023-01-05-113908_Order.php
- develop/app/Database/Migrations/2023-01-05-113916_Payment.php
- develop/app/Database/Migrations/2023-01-06-060931_Wallet.php
- develop/app/Database/Seeds/Product.php
- develop/app/Database/Seeds/Wallet.php
- develop/app/Filters/UserFilter.php
- develop/app/Services/User.php
- develop/composer.lock
Database migrations and seeds implemented.
Service logic user filter implemented.
Service logic api route implemented.
**Checklist:**
> develop: Service logic database field creation , user filter creation and service logic route creation

- develop/app/Controllers/v2/OrderController.php
- develop/app/Controllers/v2/ProductController.php
- develop/app/Entities/v2/OrderEntity.php
- develop/app/Models/v2/OrderModel.php
1.  Implement Order service logic.
**Checklist:**
> dev: Develop Order Service.

- develop/app/Controllers/v2/OrderController.php
- develop/app/Controllers/v2/PaymentController.php
- develop/app/Controllers/v2/WalletController.php
- develop/app/Entities/v2/PaymentEntity.php
- develop/app/Models/v2/PaymentModel.php
- develop/app/Models/v2/WalletModel.php
1.  Implement Payment service logic.
2.  Implement Wallet logic.
**Checklist:**
> dev: Develop Payment Service and Wallet logic.

- develop/app/Config/Events.php
- develop/app/Database/Migrations/initDataBase.php
- develop/app/Models/v2/OrderModel.php
- develop/app/Models/v2/PaymentModel.php
- develop/app/Models/v2/ProductModel.php
- develop/app/Models/v2/WalletModel.php
- develop/tests/API/v2/OrderTest.php
- develop/tests/API/v2/PaymentTest.php
- develop/tests/API/v2/ProductTest.php
- develop/tests/API/v2/WalletTest.php
- develop/tests/_support/DatabaseTestCase.php
1. Product service testing is done.
2. Create other services testing file.
3. Other services are on the road.
**Checklist:**
> dev:Append product service testing logic

- develop/app/Config/Routes.php
- develop/app/Controllers/v2/WalletController.php
- develop/tests/API/v2/WalletTest.php
1. Wallet service testing is done.
2. Change the WalletController show method route, because the show method of the resource route needs to pass parameters but the user key is transmitted as a header.
3. Change the WalletController show method annotation.
**Checklist:**
> dev:Wallet service testing is done.

- develop/app/Controllers/v2/ProductController.php
- develop/tests/API/v2/OrderTest.php
- develop/tests/API/v2/ProductTest.php
1. Order service testing is done.
2. append testAddInventory and testReduceInventory in the ProductTest.php
3. Modify the addInventory and reduceInventory methods in the ProductController, and assign the parameter to null if it is empty when receiving the parameter.
4. The p_key judgment in reduceInventory is repeated, and the redundant rows are deleted.
**Checklist:**
> dev:Order service testing is done.

- develop/app/Anser/Orchestrators/UserOrchestrator.php
- develop/app/Anser/Services/UserService.php
- develop/app/Config/Kint.php
- develop/app/Config/Routes.php
- develop/app/Controllers/v1/Serialize.php
- develop/app/Controllers/v1/UserOrder.php
- develop/composer.json
- develop/composer.lock
- develop/public/.htaccess
- develop/public/index.php
- src/Exception/OrchestratorException.php
- src/Orchestration/Orchestrator.php
- src/Orchestration/OrchestratorInterface.php
- src/Orchestration/Saga/Cache/BaseCacheHandler.php
- src/Orchestration/Step.php
- src/Orchestration/StepInterface.php
The Serialization of Orchestration has been implemented and executes the php-cs-fix.
> The test case will be handled in next PR.
**Checklist:**
> Dev: The Serialization of Orchestration has been implemented.

- develop/tests/API/v2/ProductTest.php
1. Refactor product service testing.
**Checklist:**
> Refactor: Product Service Tesing.

- develop/tests/API/v2/OrderTest.php
- develop/tests/API/v2/ProductTest.php
1. Refactor order service testing.
**Checklist:**
> Refactor:Order Service Testing

- develop/tests/API/v2/PaymentTest.php
1. Refactor payment service testing.
**Checklist:**
> Refactor:Payment Service Testing.

- develop/tests/API/v2/WalletTest.php
1. Refactor wallet service testing.
**Checklist:**
> Refactor:Wallet Service Testing.

- develop/app/Database/Migrations/2023-01-05-113908_Order.php
- develop/app/Database/Migrations/2023-01-05-113916_Payment.php
- develop/app/Database/Seeds/Product.php
1. Order and Payment migration remove foreign key.
2. Product seed's fake data product name field replaced from productName to productName().
**Checklist:**
> Fix:Adjust the foreign key of the database table.

- develop/app/Anser/Orchestrators/v2/CreateOrderOrchestrator.php
- develop/app/Anser/Services/v2/ProductService.php
- develop/app/Config/Routes.php
- develop/public/openapi.yaml
1. Anser product service is implement.
2.  Modify API file errors.
**Checklist:**
> dev:Anser Product Service is done,and modify API file errors.

- develop/app/Anser/Services/v2/PaymentService.php
1. Anser payment service is implement.
**Checklist:**
> Dev:Anser Payment Service is done.

- develop/app/Anser/Sagas/v2/CreateOrderSaga.php
1. CreateOrderSaga Completed.
**Checklist:**
> Dev:CreateOrderSaga Completed.

- develop/app/Anser/Orchestrators/v1/UserOrchestrator.php
- develop/app/Anser/Orchestrators/v2/CreateOrderOrchestrator.php
- src/Orchestration/Orchestrator.php
- src/Orchestration/Saga/Cache/CacheFactory.php
- src/Orchestration/Saga/Saga.php
- src/Orchestration/Saga/SagaInterface.php
- src/Orchestration/Saga/SimpleSaga.php
- src/Orchestration/Saga/SimpleSagaInterface.php
- src/Orchestration/Saga/State.php
- src/Orchestration/Saga/StateInterface.php
- src/Orchestration/Step.php
- src/Orchestration/StepInterface.php
1. Add `setRuntimeOrchestrator()` and `__sleep` function for `Step`, `Status`, `SimpleSaga` class.
2. Add `wakeup` function for `Orchestrator` class.
3. Change the cache instance implementation way.
4. Extract the closure of orchestrator step.
> Finally get the serialize successfully result! :tada::tada::tada:
**Checklist:**
> Enhance: Solve serialize problem.

- develop/app/Anser/Orchestrators/v2/CreateOrderOrchestrator.php
- develop/app/Anser/Sagas/v2/CreateOrderSaga.php
- develop/app/Anser/Services/v2/OrderService.php
- develop/app/Anser/Services/v2/PaymentService.php
- develop/app/Anser/Services/v2/ProductService.php
- develop/app/Config/Routes.php
- develop/app/Controllers/v2/CreateOrderRestarter.php
- develop/app/Controllers/v2/WalletController.php
- develop/app/Database/Migrations/2023-01-06-060931_Wallet.php
- develop/tests/Anser/Orchestration/Saga/Cache/Redis/RedisHandlerTest.php
- src/Exception/OrchestratorException.php
- src/Exception/RedisException.php
- src/Exception/RestarterException.php
- src/Exception/SagaException.php
- src/Orchestration/Orchestrator.php
- src/Orchestration/OrchestratorInterface.php
- src/Orchestration/Saga/Cache/CacheHandlerInterface.php
- src/Orchestration/Saga/Cache/Redis/RedisHandler.php
- src/Orchestration/Saga/Restarter/Restarter.php
- src/Orchestration/Saga/Restarter/RestarterInterface.php
- src/Orchestration/Saga/Saga.php
1. Refactor the restarter logic.
2. Refactor the Redis handler logic and add the test case for it.
3. Add the exception and comment for Saga class.
4. Add the orchestrator restarter logic.
> The next PR will..
1. Add the orchestrator number at every services and it's datatable to let saga can compensate successfully.
2. Add the orchestrator number at without Saga Scenario.
3. Run restart by restarter successfully.
**Checklist:**
> Refactor: Refactor the restarter logic.

- develop/app/Anser/Services/v1/UserService.php
- develop/app/Anser/Services/v2/OrderService.php
- develop/app/Anser/Services/v2/PaymentService.php
- develop/app/Anser/Services/v2/ProductService.php
- develop/app/Config/Routes.php
- develop/app/Controllers/v2/CreateOrder.php
- develop/app/Controllers/v2/HistoryController.php
- develop/app/Controllers/v2/OrderController.php
- develop/app/Controllers/v2/PaymentController.php
- develop/app/Controllers/v2/ProductController.php
- develop/app/Controllers/v2/WalletController.php
- develop/app/Database/Migrations/2023-02-24-050603_OrderHistory.php
- develop/app/Database/Migrations/2023-02-24-050623_PaymentHistory.php
- develop/app/Database/Migrations/2023-02-24-070229_WalletHistory.php
- develop/app/Database/Migrations/2023-02-24-072359_InventoryHistory.php
- develop/app/Entities/v2/InventoryHistoryEntity.php
- develop/app/Entities/v2/OrderHistoryEntity.php
- develop/app/Entities/v2/PaymentHistoryEntity.php
- develop/app/Entities/v2/WalletHistoryEntity.php
- develop/app/Models/v2/InventoryHistoryModel.php
- develop/app/Models/v2/OrderHistoryModel.php
- develop/app/Models/v2/OrderModel.php
- develop/app/Models/v2/PaymentHistoryModel.php
- develop/app/Models/v2/PaymentModel.php
- develop/app/Models/v2/ProductModel.php
- develop/app/Models/v2/WalletHistoryModel.php
- develop/app/Models/v2/WalletModel.php
1. Append history logic into service method.
2. Change anser service action method  param passing
3. Add the order,payment,wallet,inventory history migration file.
4. Add the Entities of order,payment,wallet,inventory.
5. Add the Models of order,payment,wallet,inventory.
6. Modified the anser service some method code format.
7. Append history controller to enable the get history method.
8. Modified Config/Route.php to append history routes.
**Checklist:**
> Dev:Append history logic into service method.

- develop/app/Controllers/v2/HistoryController.php
- develop/app/Controllers/v2/OrderController.php
- develop/app/Controllers/v2/PaymentController.php
- develop/app/Controllers/v2/ProductController.php
- develop/app/Controllers/v2/WalletController.php
- develop/app/Entities/v2/OrderHistoryEntity.php
1. Fix HistoryController return data and status.
2. Append orch_key get primary key logic in service some method.
**Checklist:**
> Modified: Fix HistoryController response and service api logic.

- develop/app/Anser/Orchestrators/v2/CreateOrderOrchestrator.php
- develop/app/Anser/Sagas/v2/CreateOrderSaga.php
- develop/app/Anser/Services/v2/OrderService.php
- develop/app/Anser/Services/v2/PaymentService.php
- develop/app/Anser/Services/v2/ProductService.php
- develop/app/Config/Routes.php
- develop/app/Controllers/v2/CreateOrderRestarter.php
- develop/app/Controllers/v2/ProductController.php
- src/Orchestration/Orchestrator.php
- src/Orchestration/OrchestratorInterface.php
- src/Orchestration/Saga/Restarter/Restarter.php
- src/Orchestration/Saga/Restarter/RestarterInterface.php
1. Add the service of action to support Saga compensation.
2. The restarter refactor finished.
3. The restarter of createOrder has been design.
>The restarter can run successfully in every experiment scenario!! 🎉 🎉 🎉 
**Checklist:**
> Develop: The restarter has been implement and run successfully!

- src/Exception/SagaException.php
- src/Orchestration/Orchestrator.php
- src/Orchestration/Saga/Saga.php
- src/Orchestration/Saga/State.php
- src/Orchestration/Saga/StateInterface.php
Fix some bug of Saga component.
> It can run normally and need some test case.
**Checklist:**
> Fix: Fix some bug of Saga component

- composer.json
Dev: Add the dependency package.
> Dev: Add the dependency package.

- develop/app/Anser/Orchestrators/v2/CreateOrderOrchestrator.php
- develop/app/Controllers/v2/CreateOrderRestarter.php
- src/Exception/OrchestratorException.php
- src/Orchestration/Orchestrator.php
- src/Orchestration/Saga/Restarter/Restarter.php
- src/Orchestration/Step.php
Fix: Fix some Step bug and restarter bug
**Checklist:**
> Fix: Fix some Step bug and restarter bug
